import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "./_components/theme-provider";
import Navbar from "./_components/Navbar";
import prisma from '@/app/lib/db';
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import "./globals.css";
import { cn } from "@/lib/utils";
import { unstable_noStore as noStore } from 'next/cache'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getData(userId: string) {
  if(userId) {
    const data =  await prisma.user.findUnique({
       where: { id: userId },
       select: { colorSchema: true }
     });
   
      return data;
  }
}

export default async function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  noStore();
  const { getUser } = getKindeServerSession();
  const user = await getUser();

  const data = await getData(user?.id as string);

  return (
    <html lang="en">
      <body className={cn(`${inter.className} ${data?.colorSchema ?? "theme-blue"}`)}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
          <Navbar/>
          <main className="min-h-dvh w-full flex flex-col ">
            {children}
          </main>
        </ThemeProvider>
        </body>
    </html>
  );
}
